
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifrjgyjmggmhtvnlyntf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmcmpneWptZ2dtaHR2bmx5bnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODEwOTcsImV4cCI6MjA2NDY1NzA5N30.6PZFb8r5PvqM0QPQgqSeTnUDL-ZhHocQBcx_WN9hEhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
