// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzqmzpozhlyvbxguhltf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cW16cG96aGx5dmJ4Z3VobHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDY5NTUsImV4cCI6MjA2MTQ4Mjk1NX0.P_8S90XZSKyf_Rk6r-VrTO4TN-03IJleufws7hdtemQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);