// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdenmbvnvedzmmdmheub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZW5tYnZudmVkem1tZG1oZXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjY5NzEsImV4cCI6MjA2MzIwMjk3MX0.tiFDQLFzhM2C5lVs71yQ_nXJnPG0hrD94-DuZGG8wYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);